# Generated by Django 3.2.23 on 2023-11-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_contact_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basic_info',
        ),
    ]
