# Generated by Django 3.2.23 on 2023-12-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_basic_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=20)),
                ('problem_definition', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact_info',
        ),
    ]
