# Generated by Django 3.2.23 on 2023-12-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20231206_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=20)),
                ('problem_definition', models.TextField()),
                ('problem', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('reff_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
