# Generated by Django 3.2.23 on 2023-12-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20231207_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='problem_definition',
        ),
    ]
